---
apiVersion: apps/v1	
kind: Deployment	
metadata:	
  name: ui	
  namespace: dev	
spec:	
  replicas: 1	
  selector:	
    matchLabels:	
      app: ui	
  template:	
    metadata:	
      labels:	
        app: ui	
    spec:	
      containers:	
      - name: ui	
        image: tntaksreg.azurecr.io/ui:latest	
        ports:	
        - containerPort: 8080	

---
apiVersion: v1	
kind: Service	
metadata:	
  name: ui-service	
  namespace: dev	
spec:	
  type: ClusterIP	
  selector:	
    app: ui	
  ports:	
    - protocol: TCP	
      port: 80	
      targetPort: 8080	

---
apiVersion: networking.k8s.io/v1beta1	
kind: Ingress	
metadata:	
  name: ui-ingress	
  namespace: dev	
  annotations:	
    kubernetes.io/ingress.class: addon-http-application-routing	
spec:	
  rules:	
  - host: ui.e46708b92c054086909b.eastus.aksapp.io	
    http:	
      paths:	
      - backend:	
          serviceName: ui-service	
          servicePort: 8080
        path: /
