---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deployment
  namespace: dev
spec:
  selector:
    matchLabels:
      app: ui-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: ui-deployment
    spec:
      containers:
      - name: ui-pods
        image: nginx
---
apiVersion: v1
kind: Service
metadata:
    name: ui-service
spec:
  selector:
    app: ui-deployment
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ui-ingress
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
  - host: ui.e46708b92c054086909b.eastus.aksapp.io
    http:
      paths:
      - backend:
          serviceName: ui-service
          servicePort: 80
        path: /
