---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-deployment
spec:
  selector:
    matchLabels:
      app: sample-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: sample-deployment
    spec:
      containers:
      - name: pods-sample-deployment
        image: nginx
---
apiVersion: v1
kind: Service
metadata:
    name: service-sample
spec:
  selector:
    app: sample-deployment
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
